
[[terms]]
== Terms and definitions


The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and  "OPTIONAL" in this document are to be interpreted as described in <<RFC2119>>.

The notation used in this memo to (re-)define iCalendar elements is
the ABNF notation of <<RFC5234>> as used by <<RFC5545>>.  Any syntax
elements shown below that are not explicitly defined in this
specification come from iCalendar <<RFC5545>>.

Additionally, the following terms are used:

=== participant

Represents an agent that takes part in scheduling or publishing. A participant may be a human, for example an attendee, or a resource, for example a conference room.

=== publishable

A component which takes part in <<RFC5546>> publishing operations.

=== schedulable

A component which takes part in <<RFC5546>> scheduling operations.

=== owner

The "Owner" of a "Schedulable" component is equivalent to the "Organizer" in <<RFC5546>>. As such, there may be only one "Owner" though future specifications may relax or extend that constraint. The "Owner" is indicated by a role of "OWNER".
