
[[icalendar-extensions]]
== iCalendar Extensions

=== New Property Parameters

[[new-prop-para-required]]
==== Required

Parameter name:: REQUIRED

Purpose:: To specify whether the associated property is required in
  the current context.

Format Definition::
This parameter is defined by the following notation:
[source,abnf]
----
requirededparam = "REQUIRED"  "=" ("TRUE" / "FALSE")
  ; Default is FALSE
----

Description:: This parameter MAY be specified on REPLY-URL and, if
  the value is TRUE, indicates the organizer requires all replies to
  be made via the specified service rather than iTip replies.

[[new-prop-para-stay-informed]]
==== Stay-Informed

Parameter name:: STAY-INFORMED

Purpose:: To specify the voter also wants to be added as an ATTENDEE
  when the poll is confirmed.

Format Definition::
This parameter is defined by the following notation:
[source,abnf]
----
stayinformedparam = "STAY-INFORMED"  "=" ("TRUE" / "FALSE")
                  ; Default is FALSE
----

Description:: This parameter MAY be specified on the CALENDAR-ADDRESS
  property in the PARTICIPANT component and, if the
  value is TRUE, indicates the voter wishes to be added to the final
  choice as a non-participant.

[[new-prop-reply-url]]
==== Reply-URL

Property name:: REPLY-URL

Purpose:: This property may be used in scheduling messages to
  indicate additional reply methods, for example a web-service.

Value type:: URI

Property Parameters:: Non-standard, required or iana parameters can
  be specified on this property.

Conformance:: This property MAY be specified in a VPOLL component.

Description:: When used in a scheduling message this property
  indicates additional or required services that can be used to
  reply.  Typically, this would be a web service of some form.

Format Definition::
This property is defined by the following notation:
[source,abnf]
----
reply-url = "REPLY-URL" reply-urlparams ":" uri CRLF

reply-urlparams = *(
                  (";" requiredparam) /
                  (";" other-param)
                  )
----
