[[new-participant-properties-for-itip]]
== New Participant Properties for iTip

The following properties are defined to be used within PARTICIPANT during scheduling and take the place of ATTENDEE and ORGANIZER properties and parameters.

[[new-prop-kind]]
=== Kind

Property name:: KIND

Purpose:: This is what kind of entity this participant is, if known.

Property Parameters:: Non-standard or iana parameters can be
specified on this property.

Conformance:: This property MAY be specified in a "PARTICIPANT" calendar component.

Description:: When used in a "PARTICIPANT" calendar component this property indicates the kind of entity, individual, group etc. +
+
It takes the values shown below which are a redefinition of the CUTYPE parameter values defined in <<RFC5545>> and aligned with <<RFC8984>> .

Format Definition::
This property is defined by the following notation:
[source,abnf]
----
kind = "KIND" kindparams ":"
                "INDIVIDUAL"   ; An individual
              / "GROUP"        ; A group of individuals
              / "RESOURCE"     ; A physical resource
              / "LOCATION"     ; A location resource e.g a room
              / iana-token CRLF

kindparams = *(";" other-param)
----

[[new-prop-participation-status]]
=== Participation-status

Property name:: PARTICIPATION-STATUS

Purpose:: This property is used in the "PARTICIPANT" calendar component to indicate the participation status - if any.

Property Parameters:: Non-standard or iana parameters can be
specified on this property.

Conformance:: This property MAY be specified in a "PARTICIPANT" calendar component.

Description:: When used in a "PARTICIPANT" calendar component this property indicates what
status, if any, the participant has. +
+
It takes the same values as the PARTSTAT parameter defined in <<RFC5545>>.

Format Definition::
This property is defined by the following notation:
[source,abnf]
----
participation-status = "PARTICIPATION-STATUS"
                       participation-statusparams ":"
              NEEDS-ACTION / ; No status
                    ; has yet been set by the participant.

              ACCEPTED / ; The invited
                    ; participant will participate.
              DECLINED / ; The invited
                    ; participant will not participate.
               TENTATIVE / ; The invited participant
                     ; may participate.
                DELEGATED / ; The invited participant
                     ; has delegated their attendance to
                     ; another participant, as specified
                      ; in the PARTICIPATION-DELEGATED-TO property.
                COMPLETED / ; The assigned task is
                     ; completed.
                IN-PROCESS / ; The assigned task is
                     ; being worked on.
                    iana-token ("," iana-token) CRLF

participation-statusparams = *(";" other-param)
----

[[new-prop-participation-delegated-from]]
=== Participation delegated from

Property name:: PARTICIPATION-DELEGATED-FROM

Purpose:: This property is used in the "PARTICIPANT" calendar component to indicate who has delegated their participation to this participant.

Property Parameters:: Non-standard or iana parameters can be
specified on this property.

Conformance:: This property MAY be specified in a "PARTICIPANT" calendar component 0 or more times.

Description:: This property specifies a calendar
user that has delegated their participation in a group-scheduled
component to the calendar user specified by the component.

Format Definition::
This property is defined by the following notation:
[source,abnf]
----
participation-delfrom = "PARTICIPATION-DELEGATED-FROM"
                        participation-delfromparams ":"
              CAL-ADDRESS
              iana-token ("," iana-token) CRLF

participation-delfromparams = *(";" other-param)
----

[[new-prop-participation-delegated-to]]
=== Participation delegated to

Property name:: PARTICIPATION-DELEGATED-TO

Purpose:: To specify the calendar user to whom the calendar user
specified by the component has delegated participation.

Property Parameters:: Non-standard or iana parameters can be
specified on this property.

Conformance:: This property MAY be specified in a "PARTICIPANT" calendar component 0 or more times.

Description:: This property specifies the calendar
user that has been delegated participation in a group-scheduled
component by the calendar user specified by the component.

Format Definition::
This property is defined by the following notation:
[source,abnf]
----
participation-delto = "PARTICIPATION-DELEGATED-TO"
                      participation-deltoparams ":"
              CAL-ADDRESS
              iana-token ("," iana-token) CRLF

participation-deltoparams = *(";" other-param)
----

[[new-prop-member-of]]
=== Member of

Property name:: MEMBER-OF

Purpose:: To specify the group or list membership of the calendar
user specified by the component.

Property Parameters:: Non-standard or iana parameters can be
specified on this property.

Conformance:: This property MAY be specified in a "PARTICIPANT" calendar component 0 or more times.

Description:: This property identifies the group or
list membership for the calendar user specified by the component.

Format Definition::
This property is defined by the following notation:
[source,abnf]
----
member-of = "MEMBER-OF" member-ogparams ":"
              CAL-ADDRESS
              iana-token ("," iana-token) CRLF

memberofparams = *(";" other-param)
----

[[new-prop-lang]]
=== Lang

Property name:: LANG

Purpose:: This is the language tag, as defined in <<RFC5646>>, that best describes the participant's preferred language, if known.

Property Parameters:: Non-standard or iana parameters can be
specified on this property.

Conformance:: This property MAY be specified in any appropriate component.

Format Definition::
This property is defined by the following notation:
[source,abnf]
----
lang = "LANG" langparams ":" TEXT CRLF

langparams = *(";" other-param)
----

[[new-prop-expect-reply]]
=== Expect reply

Property name:: EXPECT-REPLY

Purpose:: If true, the organizer is expecting the participant to notify them of their participation status.

Property Parameters:: Non-standard or iana parameters can be
specified on this property.

Conformance:: This property MAY be specified once in the "PARTICIPANT" calendar component.

Format Definition::
This property is defined by the following notation:
[source,abnf]
----
expect-reply = "EXPECT-REPLY"
              expect-replyparams ":"
              ( "TRUE" / "FALSE") CRLF

expect-replyparams = *(";" other-param)
----


[[new-prop-scheduling-agent]]
=== Scheduling-agent

Property name:: SCHEDULING-AGENT

Purpose:: This is who is responsible for sending scheduling messages with this calendar object to the participant.

Property Parameters:: Non-standard or iana parameters can be
specified on this property.

Conformance:: This property MAY be specified once in the "PARTICIPANT" calendar component.

Format Definition::
This property is defined by the following notation:
[source,abnf]
----
scheduling-agent = "SCHEDULING-AGENT"
              scheduling-agentparams ":"
              ( "SERVER" /
                "CLIENT" /
                "NONE") CRLF

scheduling-agentparams = *(";" other-param)
----

The value MUST be one of the following values from the registry defined in <<RFC6638, section=12.4.1>>, or a vendor-specific value.

SERVER::
The calendar server will send the scheduling messages.

CLIENT::
The calendar client will send the scheduling messages.

NONE::
No scheduling messages are to be sent to this participant.


[[new-prop-scheduling-force-send]]
=== Scheduling-force-send

Property name:: SCHEDULING-FORCE-SEND

Purpose:: A client may set the property on a participant to true to request that the server send a scheduling message to the participant when it would not normally do so (e.g., if no significant change is made the object or the scheduleAgent is set to client). The property MUST NOT be stored in the object on the server or appear in a scheduling message.

Property Parameters:: Non-standard or iana parameters can be
specified on this property.

Conformance:: This property MAY be specified once in the "PARTICIPANT" calendar component.

Format Definition::
This property is defined by the following notation:
[source,abnf]
----
scheduling-force-send = "SCHEDULING-FORCE-SEND"
              scheduling-force-sendparams ":"
              ( "TRUE" / "FALSE") CRLF

scheduling-force-sendparams = *(";" other-param)
----

Description::
This property MAY be specified in "PARTICIPANT" calendar components
for which the "SCHEDULE-AGENT" property is set to the value
"SERVER" or is absent. This property is used to force a server
to send a scheduling message to a specific calendar user in
situations where the server would not send a scheduling message
otherwise (e.g., when no change that warrants the delivery of
a new scheduling message was performed on the scheduling object
resource). An "Owner" MAY specify this property for a
PARTICIPANT with the value "REQUEST" to force a "REQUEST"
scheduling message to be sent to the user.
+
Participants who are not the "Owner" MAY specify this property
in the "Owner" PARTICIPANT with the value "REPLY" to force a
"REPLY" scheduling message to be sent to the "Owner".
+
Servers MUST NOT preserve this property in scheduling
object resources, nor include it in any scheduling messages sent
as the result of a scheduling operation.
+
Clients MUST NOT include this property in any scheduling messages
 that they themselves send.
+
Servers MUST set the "SCHEDULING-STATUS" property of the
participant to 2.5 (i.e., "Success; unknown, non-standard
property value ignored."; see <<RFC5546, section=3.6.6>>) when
the "SCHEDULE-FORCE-SEND" property is set to an iana-token
value they do not recognize.

[[new-prop-scheduling-status]]
=== Scheduling-status

Property name:: SCHEDULING-STATUS

Purpose:: This is a list of status codes, returned from the processing of the most recent scheduling message sent to this participant. The status codes MUST be valid statcode values as defined in the ABNF in Section 3.8.8.3 of [RFC5545].
+
Servers MUST only add or change this property when they send a scheduling message to the participant. Clients SHOULD NOT change or remove this property if it was provided by the server. Clients MAY add, change, or remove the property for participants where the client is handling the scheduling.This property MUST NOT be included in scheduling messages.

Property Parameters:: Non-standard or iana parameters can be
specified on this property.

Conformance:: This property MAY be specified in any appropriate component.

Format Definition::
This property is defined by the following notation:
[source,abnf]
----
scheduling-status = "SCHEDULING-STATUS"
            scheduling-statusparams ":" TEXT CRLF

scheduling-statusparams = *(";" other-param)
----

[[new-prop-scheduling-dtstamp]]
=== Scheduling-dtstamp

Property name:: SCHEDULING-DTSTAMP

Purpose:: This is the timestamp for the most recent response from this participant.
+
This is the updated property of the last response when using iTIP. It can be compared to the updated property in future responses to detect and discard older responses delivered out of order.

Property Parameters:: Non-standard or iana parameters can be
specified on this property.

Conformance:: This property MAY be specified in any appropriate component.

Format Definition::
This property is defined by the following notation:
[source,abnf]
----
scheduling-dtstamp = "SCHEDULING-DTSTAMP"
            scheduling-dtstampparams ":" DATE-TIME CRLF

scheduling-dtstampparams = *(";" other-param)
----


[[new-prop-invited-by]]
=== Invited-by

Property name:: INVITED-BY

Purpose:: This is the calendar address of the participant who added this participant to the entity, if known.

Property Parameters:: Non-standard or iana parameters can be
specified on this property.

Conformance:: This property MAY be specified in any appropriate component.

Format Definition::
This property is defined by the following notation:
[source,abnf]
----
invited-by = "INVITED-BY"
            invited-byparams ":" CAL-ADDRESS CRLF

invited-byparams = *(";" other-param)
----

